-- 코드를 입력하세요
SELECT a.CAR_ID, a.CAR_TYPE, ROUND(a.DAILY_FEE*30*(100-c.DISCOUNT_RATE)/100) AS FEE
from CAR_RENTAL_COMPANY_CAR a inner join CAR_RENTAL_COMPANY_RENTAL_HISTORY b on a.CAR_ID = b.CAR_ID inner join CAR_RENTAL_COMPANY_DISCOUNT_PLAN c on a.CAR_TYPE = c.CAR_TYPE
WHERE a.CAR_ID not in (
    select CAR_ID
    from CAR_RENTAL_COMPANY_RENTAL_HISTORY
    where END_DATE > '2022-11-01' and START_DATE < '2022-12-01'
) and c.DURATION_TYPE = "30일 이상"
GROUP BY a.CAR_ID
HAVING a.CAR_TYPE IN ('세단', 'SUV') AND (FEE>=500000 AND FEE<2000000) 
ORDER BY FEE DESC, a.CAR_TYPE ASC, a.CAR_ID DESC;