

SELECT f.FLAVOR
FROM FIRST_HALF f left join JULY j on f.FLAVOR = j.FLAVOR
group by f.FLAVOR
HAVING SUM(f.TOTAL_ORDER) + COALESCE(SUM(j.TOTAL_ORDER), 0) > 0
ORDER BY SUM(f.TOTAL_ORDER) + COALESCE(SUM(j.TOTAL_ORDER), 0) DESC
LIMIT 3;
