-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) as TOTAL_SALES
from USED_GOODS_BOARD ub left join USED_GOODS_USER uu on ub.WRITER_ID = uu.USER_ID
where ub.STATUS = "DONE"
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
order by TOTAL_SALES