-- 코드를 입력하세요
SELECT fp.PRODUCT_ID,  fp.PRODUCT_NAME, SUM(fo.AMOUNT*fp.PRICE) as TOTAL_SALES
from FOOD_PRODUCT fp, FOOD_ORDER fo
where fp.PRODUCT_ID = fo.PRODUCT_ID and fo.PRODUCE_DATE >= '2022-05-01' AND fo.PRODUCE_DATE < '2022-06-01'
GROUP BY fp.PRODUCT_ID
order by TOTAL_SALES desc, fp.PRODUCT_ID